import React from 'react';
import { Inter } from 'next/font/google';
import { Metadata } from 'next';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

const RootLayout: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className} style={{ 
        backgroundImage: 'url(/background_paper.jpg)', 
        backgroundSize: '100% 100%', // Stretch the background image to fit the size of the screen
        backgroundPosition: 'center', // Center the background image
        backgroundRepeat: 'no-repeat', // Prevent background image from repeating
        overflow: 'hidden', // Hide overflow to ensure the background image covers the entire viewport
        height: '100vh', // Make sure the body covers the full viewport height
        width: '100vw'
      }}>
        {children}
      </body>
    </html>
  );
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default RootLayout;
